# Generated by Django 4.0.3 on 2022-04-23 00:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
